### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xxxxsssssx** [huchenlei/sd-forge-ic-light#15]
Sorry, but the error code was very long, so I am including part of it here.(all code is including to textfile.)
*** Error completing request
*** Arguments: ('task(oryrbm1cncv9ffn)', <gradio.routes.Request object at 0x000001A943CC5FF0>, '(prompt is here)', [], 40, 'Euler a', 1, 1, 7, 768, 1536, False, 0.7, 1.5, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, {'enabled': True, 'model_type': 'FC', 'input_fg': array([[[112, 124, 140, 255],
***         [112, 124, 140, 255],
***         [112, 124, 140, 255],
***         ...,
***         [ 93,  93, 100, 255],
***         [ 93,  93, 100, 255],
***         [ 93,  93, 101, 255]],
***
***        [[112, 123, 140, 255],
***         [112, 124, 140, 255],
***         [112, 124, 140, 255],
***         ...,
***         [ 91,  91,  98, 255],
***         [ 91,  91,  98, 255],
***         [ 91,  92,  99, 255]],
***
***        [[111, 123, 139, 255],
***         [112, 123, 139, 255],
***         [112, 124, 140, 255],
***         ...,
***         [ 89,  89,  97, 255],
***         [ 89,  89,  96, 255],
***         [ 89,  89,  97, 255]],
***
***        ...,
***
***        [[192, 179, 172, 255],
***         [192, 178, 171, 255],
***         [192, 179, 172, 255],
***         ...,
***         [255, 255, 243, 255],
***         [255, 255, 243, 255],
***         [255, 255, 244, 255]],
***
***        [[192, 179, 172, 255],
***         [193, 179, 172, 255],
***         [193, 179, 172, 255],
***         ...,
***         [255, 255, 243, 255],
***         [255, 255, 243, 255],
***         [255, 255, 243, 255]],
***
***        [[192, 179, 171, 255],
***         [192, 179, 172, 255],
***         [192, 178, 171, 255],
***         ...,
***         [255, 255, 243, 255],
***         [255, 255, 243, 255],
***         [255, 255, 243, 255]]], dtype=uint8), 'uploaded_bg': None, 'bg_source_fc': 'None', 'bg_source_fbc': 'Use Background Image', 'remove_bg': True}, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui-forge-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable
[message (1).txt](https://github.com/huchenlei/sd-forge-ic-light/files/15467209/message.1.txt)

forge  version: [f0.0.17v1.8.0rc-1.7.0] •  python: 3.10.7  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •

If more information is needed, I`ll send it.
sorry.

**Comment by Zyin055** [comment]
Are you using an SDXL model? It only works with SD1.5 models.

**Comment by xxxxsssssx** [comment]
I am very sorry.
I thought it also works with SDXL.
thank you.
