### ISSUE TITLE
Out of Memory in a1111 webui after multiple inference with this extension

### ISSUE THREAD

**Issue by greasebig** [huchenlei/sd-forge-ic-light#17]

**Comment by greasebig** [comment]
![image](https://github.com/huchenlei/sd-forge-ic-light/assets/121388156/c527be23-9f29-4051-a1a0-9eab3ba078f6)

memory leak
i record VM after every inference

**Comment by huchenlei** [comment]
I guess the next pressing thing would be porting forge's vram management system 😅

**Comment by tanggogogo123** [comment]
> 我想下一个紧迫的事情是移植 forge 的 vram 管理系统 😅

希望能解决这个问题，因为12G的显存就第一次起作用，之后就不起作用了，必须要关掉后台重启才行

**Comment by tanggogogo123** [comment]
> I guess the next pressing thing would be porting forge's vram management system 😅

希望能解决这个问题，因为12G的显存就第一次起作用，之后就不起作用了，必须要关掉后台重启才行

**Comment by huchenlei** [comment]
Fixed in https://github.com/huchenlei/sd-webui-model-patcher/commit/0a85cf6444bf7fe5fb10884b9160fc38da82b153

Update your sd-webui-model-patcher should fix the issue now.
