### ISSUE TITLE
after updating 6.7 version, it doesn't work occasionally at the first inference right after launching webui

### ISSUE THREAD

**Issue by greasebig** [huchenlei/sd-forge-ic-light#25]
seem like it didn't load iclight and directly text2img generate

**Comment by greasebig** [comment]
<img width="706" alt="image" src="https://github.com/huchenlei/sd-forge-ic-light/assets/121388156/a7c8d752-5cd0-4a81-9bc8-9fdd478b3343">
<img width="1371" alt="image" src="https://github.com/huchenlei/sd-forge-ic-light/assets/121388156/9a4e82e7-1816-46ed-aaf8-77d65b514d6b">

it is kinda amusing :)

**Comment by greasebig** [comment]
i find out the reason: EVERYTIME restart webui, you must click Restore Details button，and it will work later.
definitely bug

**Comment by sbcdba** [comment]
forge work error #
![微信图片_20240608145039](https://github.com/huchenlei/sd-forge-ic-light/assets/131692431/4cef998a-aa89-4936-8509-7ab1096955ba)

**Comment by greasebig** [comment]
i dont know why, but today i test again your extension work well

**Comment by greasebig** [comment]
today, i meet the problem again. but it seems to occur occasionally

**Comment by hben35096** [comment]
For use in A1111, A1111 version:
feee37d75f1b168768014e4634dcb156ee649c05

sd-forge-ic-light  version:
b8268e16a0b99ed7dffff930a18ad475372a49ae
is working normally
![image](https://github.com/huchenlei/sd-forge-ic-light/assets/139383150/9fea9729-ed09-4c94-a405-452efb38ee58)
---
But since the sd-forge-ic-light  version:
53d13bbf26383bbbfeea6ea49a1e3adff68e4e13
![image](https://github.com/huchenlei/sd-forge-ic-light/assets/139383150/e646bfcb-446f-42f1-a063-83f0ab12df5b)

**Comment by ivanoff13** [comment]
![Снимок](https://github.com/huchenlei/sd-forge-ic-light/assets/20181974/05440813-7b42-4cdc-ac77-790156e2bfee)
It stopped working today

**Comment by ToniVacaESAT** [comment]
I have the same problem. For now I have reinstalled it and it continues to ignore it

**Comment by Haoming02** [comment]
The latest version now uses `process_before_every_sampling`, which is currently only in **Forge**, and will be added to Automatic1111 **v1.10**.

So for now, you can revert to the older version of **IC-Light** extension, or use the **1.10-RC** branch of Automatic11111

**Comment by greasebig** [comment]
hi, any solution for my problem?

**Comment by greasebig** [comment]
it is so obvious that i can reproduce it with 50% Success rate
