### ISSUE TITLE
can this extension be installed in stable diffusion webui?

### ISSUE THREAD

**Issue by prog-ape** [huchenlei/sd-forge-ic-light#4]
hi,can this extension be installed in stable diffusion webui?

**Comment by huchenlei** [comment]
I am working on the A1111 version right now. It will reuse the UI code, but backend impl needs to be adjusted.

**Comment by prog-ape** [comment]
thank you for your work

**Comment by greasebig** [comment]
> I am working on the A1111 version right now. It will reuse the UI code, but backend impl needs to be adjusted.

hello, thanks for you great work! Do you have an approximate time for the a1111 webui iclight extension to be released?
