### ISSUE TITLE
ldm_patched

### ISSUE THREAD

**Issue by wangdadx** [huchenlei/sd-forge-ic-light#6]
File "D:\stable-diffusion-webui\extensions\sd-forge-ic-light\scripts\forge_ic_light.py", line 18, in <module>
        from ldm_patched.modules.utils import load_torch_file
    ModuleNotFoundError: No module named 'ldm_patched'
没有ldm_patched这个文件那？

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/sd-forge-ic-light/issues/4

This extension is only for SD Forge. This extension is not compatible with A1111.
